### PR TITLE
Selling QoL

### PR DESCRIPTION
**Pull request by PKPenguin321**
- Shift-click an item in your inventory to instantly sell all of it
- A new setting has been added that will show an option to sell all but one of an item in your inventory when it's enabled

### CODE REVIEW

**Review by TBartl — APPROVED** [review]

**Comment by lzk228** [comment]
merge when? :trollface:

**Comment by PKPenguin321** [comment]
i forgor

**Comment by PKPenguin321** [comment]
idk why i never just merged it

**Comment by lzk228** [comment]
YEAHHH LESSGOO

**Pull request merged**
